version: 2.1
orbs:
  node: circleci/node@1.1.6
  codevoc: codecov/codecov@1.02
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/painikepeli/backend
    steps:
      - checkout:
           path: ~/painikepeli

      - node/with-cache:
          steps:
            - run: npm install

            - run: npm test

      - codecov/upload:
          file: coverage/*.json
workflows:
    build-and-test:
      jobs:
        - build-and-test
